### ISSUE TITLE
[Containment] Objects other than Notebook Entries can be saved in Notebooks

### ISSUE THREAD

**Issue by charlesh88** [topcoderinc/openmct#20]
10-18-17, during fixed issues review.

1. Create a Notebook.
1. Create a Timer, and in the dialog, save it into the Notebook. 
![screen shot 2017-10-18 at 3 04 52 pm](https://user-images.githubusercontent.com/1056412/31745065-4667b2dc-b416-11e7-800f-950474f05faa.png)

This operation should not be allowed: the Notebook should only contain Notebook entries.

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
Clear, i'm asking the edit

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
This is fixed now

**Comment by charlesh88** [comment]
Reviewed 11/07/17. Not accepted.

What's fixed: the Notebook can only contain Notebook entries, *sort of*.
What's not fixed: dragging an object to create a new Notebook entry is working as desired with respect to the Notebook entry UI itself, but it's also adding linked objects as composition children of the Notebook, which is very undesired and will become very problematic when a Notebook has a lot of entries with embedded objects. Additionally, removing the embed from an entry, or deleting an entry, fails to remove the embedded object from the Notebook. 

![screen-shot-2017-11-07-at-4 13 25-pm-annotated](https://user-images.githubusercontent.com/1056412/32525274-8c24211c-c3d8-11e7-994a-9f744baafda7.png)

What should be happening is that each entry should retain the thumb if included (which links to the snapshot) and the link (which navigates to the live object) but those elements should not be appearing as children of the Notebook in the tree. In fact, the Notebook would never display any child content in the tree.

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma Ok, i'm asking more edits.

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma This should be fixed now. 
Please check the commits: https://github.com/topcoderinc/openmct/pull/26/commits/46d7c117cbf34d3861642d9e548ebc0a9db9f8f0

And updated heroku here: https://notebook-openmct.herokuapp.com/

**Comment by charlesh88** [comment]
Reviewed 11/13/17, fixed.
