### ISSUE TITLE
[UI] New Notebook Entry dialog incomplete

### ISSUE THREAD

**Issue by charlesh88** [topcoderinc/openmct#9]
Delivery 10-10-17

Creating a new entry via an object's context menu should display a dialog as shown on Notebook UI v1.0.3 page 133, but instead looks like this:
![screen shot 2017-10-11 at 11 16 51 am](https://user-images.githubusercontent.com/1056412/31458779-ed3d5f68-ae75-11e7-8eac-5593f0f66379.png)

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
This should be fixed now, please check
![screenshot 2017-10-16 12 32 58](https://user-images.githubusercontent.com/4476442/31596673-3102b954-b26e-11e7-87bb-dd60630c7272.png)

**Comment by charlesh88** [comment]
Reviewed 10-18-17. Not accepted.

This screen is still missing the Annotate button as shown on Notebook UI v1.0.3 page 132.

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma Ok, clear

**Comment by dedywahyudi** [comment]
@charlesh88 @kbowerma 
This is fixed now

**Comment by charlesh88** [comment]
Reviewed 11/07/17, fixed.
